(function initMetadata(root, factory) {
  const api = factory();
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  root.AIImageCheckerMetadata = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function factory() {
  const KEYWORDS = [
    'c2pa',
    'jumbf',
    'content credentials',
    'openai',
    'chatgpt',
    'dall-e',
    'dalle',
    'google',
    'gemini',
    'synthid',
    'adobe',
    'xmp',
    'provenance',
    'ai-generated',
    'generated by'
  ];

  const JPEG_APP_MARKERS = new Map([
    [0xe0, 'APP0'], [0xe1, 'APP1'], [0xe2, 'APP2'], [0xe3, 'APP3'],
    [0xe4, 'APP4'], [0xe5, 'APP5'], [0xe6, 'APP6'], [0xe7, 'APP7'],
    [0xe8, 'APP8'], [0xe9, 'APP9'], [0xea, 'APP10'], [0xeb, 'APP11'],
    [0xec, 'APP12'], [0xed, 'APP13'], [0xee, 'APP14'], [0xef, 'APP15']
  ]);

  function bytes(bufferLike) {
    if (bufferLike instanceof Uint8Array) return bufferLike;
    return new Uint8Array(bufferLike);
  }

  function ascii(slice) {
    return Array.from(slice, (byte) => String.fromCharCode(byte)).join('');
  }

  function readUInt32BE(data, offset) {
    return ((data[offset] << 24) >>> 0) + (data[offset + 1] << 16) + (data[offset + 2] << 8) + data[offset + 3];
  }

  function readUInt16BE(data, offset) {
    return (data[offset] << 8) + data[offset + 1];
  }

  function detectFormat(bufferLike, fileName = '') {
    const data = bytes(bufferLike);
    const lower = fileName.toLowerCase();
    if (data.length >= 8 &&
      data[0] === 0x89 && data[1] === 0x50 && data[2] === 0x4e && data[3] === 0x47 &&
      data[4] === 0x0d && data[5] === 0x0a && data[6] === 0x1a && data[7] === 0x0a) {
      return 'png';
    }
    if (data.length >= 2 && data[0] === 0xff && data[1] === 0xd8) return 'jpeg';
    if (data.length >= 12 && ascii(data.slice(0, 4)) === 'RIFF' && ascii(data.slice(8, 12)) === 'WEBP') return 'webp';
    if (lower.endsWith('.png')) return 'png';
    if (lower.endsWith('.jpg') || lower.endsWith('.jpeg')) return 'jpeg';
    if (lower.endsWith('.webp')) return 'webp';
    return 'unknown';
  }

  function printableText(bufferLike) {
    const data = bytes(bufferLike);
    let text = '';
    for (const byte of data) {
      text += byte === 9 || byte === 10 || byte === 13 || (byte >= 32 && byte <= 126)
        ? String.fromCharCode(byte)
        : ' ';
    }
    return text.replace(/\s+/g, ' ').trim();
  }

  function collectKeywordEvidence(bufferLike) {
    const text = printableText(bufferLike);
    const lower = text.toLowerCase();
    const keywords = KEYWORDS.filter((keyword) => lower.includes(keyword));
    const evidence = keywords.map((keyword) => {
      const index = lower.indexOf(keyword);
      const start = Math.max(0, index - 32);
      const end = Math.min(text.length, index + keyword.length + 48);
      return text.slice(start, end);
    });
    return { keywords, evidence };
  }

  function parsePngChunks(bufferLike) {
    const data = bytes(bufferLike);
    const chunks = [];
    let offset = 8;
    while (offset + 8 <= data.length) {
      const length = readUInt32BE(data, offset);
      const type = ascii(data.slice(offset + 4, offset + 8));
      chunks.push(type);
      offset += 12 + length;
      if (type === 'IEND' || offset > data.length) break;
    }
    return chunks;
  }

  function parseJpegSegments(bufferLike) {
    const data = bytes(bufferLike);
    const segments = [];
    let offset = 2;
    while (offset + 3 < data.length) {
      if (data[offset] !== 0xff) {
        offset += 1;
        continue;
      }
      while (data[offset] === 0xff) offset += 1;
      const markerCode = data[offset];
      offset += 1;
      if (markerCode === 0xd9 || markerCode === 0xda) break;
      if (offset + 2 > data.length) break;
      const length = readUInt16BE(data, offset);
      if (length < 2 || offset + length > data.length) break;
      if (JPEG_APP_MARKERS.has(markerCode)) {
        segments.push({ marker: JPEG_APP_MARKERS.get(markerCode), length });
      }
      offset += length;
    }
    return segments;
  }

  function scanMetadata(bufferLike, fileName = '') {
    const format = detectFormat(bufferLike, fileName);
    const { keywords, evidence } = collectKeywordEvidence(bufferLike);
    return {
      format,
      hasDeterministicEvidence: keywords.length > 0,
      keywords,
      evidence,
      pngChunks: format === 'png' ? parsePngChunks(bufferLike) : [],
      jpegSegments: format === 'jpeg' ? parseJpegSegments(bufferLike) : []
    };
  }

  return { scanMetadata, detectFormat };
});
