const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { execFileSync, spawnSync } = require('node:child_process');
const test = require('node:test');
const { PNG } = require('pngjs');

function writePng(filePath, textValue = '') {
  const png = new PNG({ width: 32, height: 32 });
  for (let i = 0; i < png.data.length; i += 4) {
    png.data[i] = 128;
    png.data[i + 1] = 128;
    png.data[i + 2] = 128;
    png.data[i + 3] = 255;
  }

  let buffer = PNG.sync.write(png);
  if (textValue) {
    const signature = buffer.subarray(0, 8);
    const ihdrChunkEnd = 8 + 4 + 4 + 13 + 4;
    const data = Buffer.from(`Comment\0${textValue}`, 'latin1');
    const len = Buffer.alloc(4);
    len.writeUInt32BE(data.length, 0);
    const chunk = Buffer.concat([len, Buffer.from('tEXt'), data, Buffer.alloc(4)]);
    buffer = Buffer.concat([signature, buffer.subarray(8, ihdrChunkEnd), chunk, buffer.subarray(ihdrChunkEnd)]);
  }

  fs.writeFileSync(filePath, buffer);
}

test('CLI emits JSON scan results', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'watermark-cli-'));
  const filePath = path.join(dir, 'sample.png');
  writePng(filePath, 'C2PA Content Credentials from Gemini');

  const output = execFileSync(process.execPath, ['cli.js', '--json', filePath], {
    cwd: path.resolve(__dirname, '..'),
    encoding: 'utf8'
  });
  const parsed = JSON.parse(output);

  assert.equal(parsed.results.length, 1);
  assert.equal(parsed.results[0].metadata.hasDeterministicEvidence, true);
  assert.ok(parsed.results[0].metadata.keywords.includes('c2pa'));
  assert.equal(typeof parsed.results[0].heuristics.heuristicScore, 'number');
});

test('CLI emits a readable text summary', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'watermark-cli-'));
  const filePath = path.join(dir, 'sample.png');
  writePng(filePath, 'Generated by OpenAI');

  const output = execFileSync(process.execPath, ['cli.js', filePath], {
    cwd: path.resolve(__dirname, '..'),
    encoding: 'utf8'
  });

  assert.match(output, /sample\.png/);
  assert.match(output, /Deterministic evidence: yes/);
  assert.match(output, /Heuristic risk:/);
});

test('CLI exits with code 2 when no supported readable images are scanned', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'watermark-cli-'));
  const filePath = path.join(dir, 'notes.txt');
  fs.writeFileSync(filePath, 'not an image');

  const result = spawnSync(process.execPath, ['cli.js', filePath], {
    cwd: path.resolve(__dirname, '..'),
    encoding: 'utf8'
  });

  assert.equal(result.status, 2);
  assert.match(result.stderr, /No supported readable image files/);
});
