const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const test = require('node:test');
const { PNG } = require('pngjs');

const { scanImage } = require('../src');

function writePngFixture(filePath, textValue = '') {
  const png = new PNG({ width: 32, height: 32 });
  for (let y = 0; y < png.height; y += 1) {
    for (let x = 0; x < png.width; x += 1) {
      const idx = (png.width * y + x) << 2;
      const value = (x + y) % 2 === 0 ? 120 : 136;
      png.data[idx] = value;
      png.data[idx + 1] = value;
      png.data[idx + 2] = value;
      png.data[idx + 3] = 255;
    }
  }

  let buffer = PNG.sync.write(png);
  if (textValue) {
    const signature = buffer.subarray(0, 8);
    const ihdrChunkEnd = 8 + 4 + 4 + 13 + 4;
    const ihdr = buffer.subarray(8, ihdrChunkEnd);
    const rest = buffer.subarray(ihdrChunkEnd);
    const data = Buffer.from(`Comment\0${textValue}`, 'latin1');
    const len = Buffer.alloc(4);
    len.writeUInt32BE(data.length, 0);
    const chunk = Buffer.concat([len, Buffer.from('tEXt'), data, Buffer.alloc(4)]);
    buffer = Buffer.concat([signature, ihdr, chunk, rest]);
  }
  fs.writeFileSync(filePath, buffer);
}

test('scanImage returns metadata and heuristic fields for a PNG file', async () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'watermark-check-'));
  const filePath = path.join(dir, 'sample.png');
  writePngFixture(filePath, 'Content Credentials generated by OpenAI');

  const result = await scanImage(filePath);

  assert.equal(result.filePath, filePath);
  assert.equal(result.supported, true);
  assert.equal(result.metadata.format, 'png');
  assert.equal(result.metadata.hasDeterministicEvidence, true);
  assert.ok(result.metadata.keywords.includes('openai'));
  assert.equal(typeof result.heuristics.heuristicScore, 'number');
  assert.match(result.heuristics.riskLevel, /low|medium|high/);
  assert.ok(result.heuristics.notes[0].includes('not proof'));
});
