const assert = require('node:assert/strict');
const test = require('node:test');

const { scanMetadata } = require('../src/metadata');

function jpegWithAppSegment(text) {
  const payload = Buffer.from(text, 'utf8');
  const length = Buffer.alloc(2);
  length.writeUInt16BE(payload.length + 2, 0);
  return Buffer.concat([
    Buffer.from([0xff, 0xd8]),
    Buffer.from([0xff, 0xe1]),
    length,
    payload,
    Buffer.from([0xff, 0xd9])
  ]);
}

function pngWithTextChunk(keyword, value) {
  const signature = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
  const data = Buffer.from(`${keyword}\0${value}`, 'latin1');
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length, 0);
  const type = Buffer.from('tEXt', 'ascii');
  const crc = Buffer.alloc(4);
  const endLen = Buffer.alloc(4);
  const iend = Buffer.from('IEND', 'ascii');
  return Buffer.concat([signature, len, type, data, crc, endLen, iend, crc]);
}

test('detects C2PA and JUMBF evidence inside JPEG APP segments', () => {
  const image = jpegWithAppSegment('Content Credentials c2pa manifest in JUMBF from OpenAI');

  const result = scanMetadata(image, 'sample.jpg');

  assert.equal(result.format, 'jpeg');
  assert.equal(result.hasDeterministicEvidence, true);
  assert.ok(result.keywords.includes('c2pa'));
  assert.ok(result.keywords.includes('jumbf'));
  assert.ok(result.keywords.includes('content credentials'));
  assert.deepEqual(result.jpegSegments.map((segment) => segment.marker), ['APP1']);
  assert.ok(result.evidence.some((item) => item.includes('OpenAI')));
});

test('detects provenance strings inside PNG text chunks', () => {
  const image = pngWithTextChunk('XML:com.adobe.xmp', 'Generated by Gemini with SynthID and Content Credentials');

  const result = scanMetadata(image, 'sample.png');

  assert.equal(result.format, 'png');
  assert.equal(result.hasDeterministicEvidence, true);
  assert.ok(result.pngChunks.includes('tEXt'));
  assert.ok(result.keywords.includes('gemini'));
  assert.ok(result.keywords.includes('synthid'));
  assert.ok(result.keywords.includes('content credentials'));
});

test('reports no deterministic evidence for plain bytes without provenance markers', () => {
  const image = Buffer.from([0xff, 0xd8, 0xff, 0xdb, 0x00, 0x04, 0x11, 0x22, 0xff, 0xd9]);

  const result = scanMetadata(image, 'plain.jpg');

  assert.equal(result.format, 'jpeg');
  assert.equal(result.hasDeterministicEvidence, false);
  assert.deepEqual(result.keywords, []);
  assert.deepEqual(result.evidence, []);
});
