const KEYWORDS = [
  'c2pa',
  'jumbf',
  'content credentials',
  'openai',
  'chatgpt',
  'dall-e',
  'dalle',
  'google',
  'gemini',
  'synthid',
  'adobe',
  'xmp',
  'provenance',
  'ai-generated',
  'generated by'
];

const JPEG_APP_MARKERS = new Map([
  [0xe0, 'APP0'],
  [0xe1, 'APP1'],
  [0xe2, 'APP2'],
  [0xe3, 'APP3'],
  [0xe4, 'APP4'],
  [0xe5, 'APP5'],
  [0xe6, 'APP6'],
  [0xe7, 'APP7'],
  [0xe8, 'APP8'],
  [0xe9, 'APP9'],
  [0xea, 'APP10'],
  [0xeb, 'APP11'],
  [0xec, 'APP12'],
  [0xed, 'APP13'],
  [0xee, 'APP14'],
  [0xef, 'APP15']
]);

function detectFormat(buffer, fileName = '') {
  const lower = fileName.toLowerCase();
  if (buffer.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]))) {
    return 'png';
  }
  if (buffer.length >= 2 && buffer[0] === 0xff && buffer[1] === 0xd8) {
    return 'jpeg';
  }
  if (buffer.subarray(0, 4).toString('ascii') === 'RIFF' && buffer.subarray(8, 12).toString('ascii') === 'WEBP') {
    return 'webp';
  }
  if (lower.endsWith('.png')) return 'png';
  if (lower.endsWith('.jpg') || lower.endsWith('.jpeg')) return 'jpeg';
  if (lower.endsWith('.webp')) return 'webp';
  return 'unknown';
}

function printableText(buffer) {
  return buffer
    .toString('latin1')
    .replace(/[^\x09\x0a\x0d\x20-\x7e]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function collectKeywordEvidence(buffer) {
  const text = printableText(buffer);
  const lower = text.toLowerCase();
  const keywords = KEYWORDS.filter((keyword) => lower.includes(keyword));
  const evidence = [];

  for (const keyword of keywords) {
    const index = lower.indexOf(keyword);
    const start = Math.max(0, index - 32);
    const end = Math.min(text.length, index + keyword.length + 48);
    evidence.push(text.slice(start, end));
  }

  return { keywords, evidence };
}

function parsePngChunks(buffer) {
  const chunks = [];
  let offset = 8;

  while (offset + 8 <= buffer.length) {
    const length = buffer.readUInt32BE(offset);
    const type = buffer.subarray(offset + 4, offset + 8).toString('ascii');
    chunks.push(type);
    offset += 12 + length;
    if (type === 'IEND' || offset > buffer.length) break;
  }

  return chunks;
}

function parseJpegSegments(buffer) {
  const segments = [];
  let offset = 2;

  while (offset + 3 < buffer.length) {
    if (buffer[offset] !== 0xff) {
      offset += 1;
      continue;
    }

    while (buffer[offset] === 0xff) offset += 1;
    const markerCode = buffer[offset];
    offset += 1;

    if (markerCode === 0xd9 || markerCode === 0xda) break;
    if (offset + 2 > buffer.length) break;

    const length = buffer.readUInt16BE(offset);
    if (length < 2 || offset + length > buffer.length) break;

    if (JPEG_APP_MARKERS.has(markerCode)) {
      segments.push({
        marker: JPEG_APP_MARKERS.get(markerCode),
        length
      });
    }

    offset += length;
  }

  return segments;
}

function scanMetadata(buffer, fileName = '') {
  const format = detectFormat(buffer, fileName);
  const { keywords, evidence } = collectKeywordEvidence(buffer);
  const pngChunks = format === 'png' ? parsePngChunks(buffer) : [];
  const jpegSegments = format === 'jpeg' ? parseJpegSegments(buffer) : [];

  return {
    format,
    hasDeterministicEvidence: keywords.length > 0,
    keywords,
    evidence,
    pngChunks,
    jpegSegments
  };
}

module.exports = {
  scanMetadata,
  detectFormat
};
